name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read

jobs:
  # Job 1: Erst testen und bauen (Qualitätssicherung)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: .NET Umgebung einrichten
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Abhängigkeiten wiederherstellen
        run: dotnet restore DevopsFallstudie/DevopsFallstudie/DevopsFallstudie.csproj

      - name: Code kompilieren
        run: dotnet build DevopsFallstudie/DevopsFallstudie/DevopsFallstudie.csproj --no-restore

  # Job 2: Docker Image erstellen und hochladen
  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login bei GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # WICHTIG: Hier alles kleingeschrieben, sonst gibt es den "Denied" Fehler!
          tags: ghcr.io/niklasheckmann/devopsfallstudie:latest

  # Job 3: Auf Hetzner ausrollen
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy auf Hetzner via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Login beim Server
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u niklasheckmann --password-stdin
            
            # Das neue Image ziehen
            docker pull ghcr.io/niklasheckmann/devopsfallstudie:latest
            
            # Alten Container weg, neuer Name 'devopsfallstudie-app' hin
            docker stop devopsfallstudie-app || true
            docker rm devopsfallstudie-app || true
            
            docker run -d \
              --name devopsfallstudie-app \
              -p 80:8080 \
              --restart always \
              ghcr.io/niklasheckmann/devopsfallstudie:latest